name: Package BAAH

run-name: BAAH ${{ github.ref }}

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nicegui

    - name: Run package
      run: python package.py

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: BAAH-${{ github.sha }}
        path: |
          ./dist/main/*

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: true
        name: "BAAH-${{ github.ref }}"
        tag_name: "v${{ github.ref }}+${{ secrets.GITHUB_RUN_ID }}${{ secrets.GITHUB_RUN_ATTEMPT }}"
        body: |
          ## BAAH ${{ inputs.log }}
          ${{ github.sha }}
        files: |
          ./dist/main/*
          LICENSE
