name: Package BAAH

run-name: BAAH+${{ github.run_id }}

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: "utf-8"
      PYTHONUTF8: "1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run package script
      run: python package.py

    #- name: Extract version number
    #  id: get_version
    #  run: |
    #    $version = python package.py -v
    #    echo "VERSION_NUMBER=$version" >> $env:GITHUB_OUTPUT

    #- name: Upload Build Artifacts
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: BAAH${{ steps.get_version.outputs.VERSION_NUMBER }}
    #    path: ./dist/BAAH${{ steps.get_version.outputs.VERSION_NUMBER }}/*

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') # 仅tag时构建
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        prerelease: false
        name: "${{ github.ref_name }}"
        tag_name: "${{ github.ref_name }}"
        body: |
          ## ${{ github.ref_name }}
          Commit SHA: `${{ github.sha }}`
        files: |
          ./dist/*.zip
